### ISSUE TITLE
Guide Texts doesn't changed completely whenever changed language

### ISSUE THREAD

**Issue by sandtechnology** [TeamAmeriFrance/Guide-API#114]
There have a gif that can descript this issue:
![gif](https://user-images.githubusercontent.com/20417547/44108542-5184d3a8-a02d-11e8-9398-589d68ec50a7.gif)

**Comment by TehNut** [comment]
What version are you using? Is the book written to support localization?

**Comment by sandtechnology** [comment]
I am using the latest version(1.12-2.1.7-62),the book supported localization,but the text would change after restarted the game.

**Comment by TehNut** [comment]
~~That is not the latest version.~~ Nevermind, I thought I had upped the MC version to 1.12.2. 

Either way, this was fixed in https://github.com/TeamAmeriFrance/Guide-API/commit/a87e69c2ad332ba39b1dedb2e6673833d820c49a

The only other way for this to happen would be if the book was passing localized text to the pages.

**Comment by sandtechnology** [comment]
About this guide book (code):https://github.com/TeamLapen/Vampirism/blob/1.12/src/main/java/de/teamlapen/vampirism/items/ItemVampireBook.java
The case also happened on cyclic mod,but I think it used the lang text:
https://github.com/PrinceOfAmber/Cyclic/blob/master/src/main/java/com/lothrazar/cyclicmagic/guide/GuideRegistry.java
