### ISSUE TITLE
Crash with SilentGems

### ISSUE THREAD

**Issue by gl0x** [TeamAmeriFrance/Guide-API#27]
http://pastebin.com/bawuHJ30

**Comment by gl0x** [comment]
Fixed when downgrading to GuideAPI-30, assuming SilentGems was referencing an old method or something like that.

**Comment by TehNut** [comment]
The 1.9 version of GAPI is currently undergoing lots of changes. Most of the major stuff is done, however. If mods have added support with the initial 1.9 release, they will need to update for the new changes. 

It seems this issue is just do to the refactors, so it shouldn't be a big issue for them.

**Comment by b0bst3r** [comment]
As a note for anyone coming here reading this Guide-API-1.9-2.0.0-31 and SilentsGems-1.9-2.0.10-27 work fine together.
